# This is a basic workflow to help you get started with Actions

name: ExecuteCypressFromGithubActions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E Tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2    
        with:
          browser: chrome         
          spec: cypress/integration/newtestcases/**/*
          record: true 
          parallel: true
          group: 'Actions example'
        env: 
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Uploading screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots        
      - name: Uplaoding videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
        
